/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddUpCategory: typeof import('./src/components/pages/AddUpCategory.vue')['default']
    AddUpContact: typeof import('./src/components/pages/AddUpContact.vue')['default']
    AddUpCriterion: typeof import('./src/components/pages/AddUpCriterion.vue')['default']
    AddUpDirection: typeof import('./src/components/pages/direction/AddUpDirection.vue')['default']
    AddUpFaculty: typeof import('./src/components/pages/faculty/AddUpFaculty.vue')['default']
    AddUpNotification: typeof import('./src/components/pages/AddUpNotification.vue')['default']
    AddUpRegion: typeof import('./src/components/pages/AddUpRegion.vue')['default']
    AddUpService: typeof import('./src/components/pages/AddUpService.vue')['default']
    AddUpSubject: typeof import('./src/components/pages/AddUpSubject.vue')['default']
    AppNotFound: typeof import('./src/components/ui/AppNotFound.vue')['default']
    AppTitle: typeof import('./src/components/ui/AppTitle.vue')['default']
    CActionIcon: typeof import('./src/components/ui/CActionIcon.vue')['default']
    CButton: typeof import('./src/components/ui/CButton.vue')['default']
    CDatepicker: typeof import('./src/components/form/CDatepicker.vue')['default']
    CDatepickerRange: typeof import('./src/components/form/CDatepickerRange.vue')['default']
    CDropdown: typeof import('./src/components/ui/CDropdown.vue')['default']
    CFileSelect: typeof import('./src/components/form/CFileSelect.vue')['default']
    CIcon: typeof import('./src/components/ui/CIcon.vue')['default']
    CIconButton: typeof import('./src/components/ui/CIconButton.vue')['default']
    CInput: typeof import('./src/components/form/CInput.vue')['default']
    CInputNumber: typeof import('./src/components/form/CInputNumber.vue')['default']
    CLoader: typeof import('./src/components/ui/CLoader.vue')['default']
    CModal: typeof import('./src/components/ui/CModal.vue')['default']
    CPhotoSelect: typeof import('./src/components/form/CPhotoSelect.vue')['default']
    CSelect: typeof import('./src/components/form/CSelect.vue')['default']
    CTag: typeof import('./src/components/ui/CTag.vue')['default']
    CTooltip: typeof import('./src/components/ui/CTooltip.vue')['default']
    CTreeSelect: typeof import('./src/components/form/CTreeSelect.vue')['default']
    CYearPicker: typeof import('./src/components/form/CYearPicker.vue')['default']
    DropFile: typeof import('./src/components/form/DropFile.vue')['default']
    Editor: typeof import('./src/components/main/Editor.vue')['default']
    FileShow: typeof import('./src/components/form/FileShow.vue')['default']
    FroalaEditor: typeof import('./src/components/main/FroalaEditor.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectAllRef: typeof import('./src/components/form/SelectAllRef.vue')['default']
    SelectCategory: typeof import('./src/components/form/select/SelectCategory.vue')['default']
    SelectLocation: typeof import('./src/components/form/SelectLocation.vue')['default']
    SelectRegion: typeof import('./src/components/form/select/SelectRegion.vue')['default']
    SelectRole: typeof import('./src/components/form/select/SelectRole.vue')['default']
    SelectService: typeof import('./src/components/form/select/SelectService.vue')['default']
  }
}
