/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '//': RouteRecordInfo<'//', '/', Record<never, never>, Record<never, never>>,
    '//attendance': RouteRecordInfo<'//attendance', '/attendance', Record<never, never>, Record<never, never>>,
    '//criterion': RouteRecordInfo<'//criterion', '/criterion', Record<never, never>, Record<never, never>>,
    '//direction': RouteRecordInfo<'//direction', '/direction', Record<never, never>, Record<never, never>>,
    '//faculty': RouteRecordInfo<'//faculty', '/faculty', Record<never, never>, Record<never, never>>,
    '//form': RouteRecordInfo<'//form', '/form', Record<never, never>, Record<never, never>>,
    '//profile': RouteRecordInfo<'//profile', '/profile', Record<never, never>, Record<never, never>>,
    '//profile/': RouteRecordInfo<'//profile/', '/profile', Record<never, never>, Record<never, never>>,
    '//profile/attendance': RouteRecordInfo<'//profile/attendance', '/profile/attendance', Record<never, never>, Record<never, never>>,
    '//profile/docs': RouteRecordInfo<'//profile/docs', '/profile/docs', Record<never, never>, Record<never, never>>,
    '//profile/personal-task': RouteRecordInfo<'//profile/personal-task', '/profile/personal-task', Record<never, never>, Record<never, never>>,
    '//profile/task': RouteRecordInfo<'//profile/task', '/profile/task', Record<never, never>, Record<never, never>>,
    '//profile/time-table': RouteRecordInfo<'//profile/time-table', '/profile/time-table', Record<never, never>, Record<never, never>>,
    '//profile/time-table copy': RouteRecordInfo<'//profile/time-table copy', '/profile/time-table copy', Record<never, never>, Record<never, never>>,
    '//rating/direction': RouteRecordInfo<'//rating/direction', '/rating/direction', Record<never, never>, Record<never, never>>,
    '//rating/faculty': RouteRecordInfo<'//rating/faculty', '/rating/faculty', Record<never, never>, Record<never, never>>,
    '//rating/teacher': RouteRecordInfo<'//rating/teacher', '/rating/teacher', Record<never, never>, Record<never, never>>,
    '//table': RouteRecordInfo<'//table', '/table', Record<never, never>, Record<never, never>>,
    '//table2': RouteRecordInfo<'//table2', '/table2', Record<never, never>, Record<never, never>>,
    '//task': RouteRecordInfo<'//task', '/task', Record<never, never>, Record<never, never>>,
    '//time-table': RouteRecordInfo<'//time-table', '/time-table', Record<never, never>, Record<never, never>>,
    '//user': RouteRecordInfo<'//user', '/user', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/auth/login': RouteRecordInfo<'/auth/login', '/auth/login', Record<never, never>, Record<never, never>>,
    '/auth/login-with-token': RouteRecordInfo<'/auth/login-with-token', '/auth/login-with-token', Record<never, never>, Record<never, never>>,
  }
}
