/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '//': RouteRecordInfo<'//', '/', Record<never, never>, Record<never, never>>,
    '//category/': RouteRecordInfo<'//category/', '/category', Record<never, never>, Record<never, never>>,
    '//contact': RouteRecordInfo<'//contact', '/contact', Record<never, never>, Record<never, never>>,
    '//education/': RouteRecordInfo<'//education/', '/education', Record<never, never>, Record<never, never>>,
    '//education/[id]/subject/': RouteRecordInfo<'//education/[id]/subject/', '/education/:id/subject', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '//form': RouteRecordInfo<'//form', '/form', Record<never, never>, Record<never, never>>,
    '//lesson/[id]/': RouteRecordInfo<'//lesson/[id]/', '/lesson/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '//lesson/create': RouteRecordInfo<'//lesson/create', '/lesson/create', Record<never, never>, Record<never, never>>,
    '//notification': RouteRecordInfo<'//notification', '/notification', Record<never, never>, Record<never, never>>,
    '//organization/': RouteRecordInfo<'//organization/', '/organization', Record<never, never>, Record<never, never>>,
    '//organization/add': RouteRecordInfo<'//organization/add', '/organization/add', Record<never, never>, Record<never, never>>,
    '//organization/view/[id]': RouteRecordInfo<'//organization/view/[id]', '/organization/view/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '//profile': RouteRecordInfo<'//profile', '/profile', Record<never, never>, Record<never, never>>,
    '//question/': RouteRecordInfo<'//question/', '/question', Record<never, never>, Record<never, never>>,
    '//question/add': RouteRecordInfo<'//question/add', '/question/add', Record<never, never>, Record<never, never>>,
    '//region': RouteRecordInfo<'//region', '/region', Record<never, never>, Record<never, never>>,
    '//service/': RouteRecordInfo<'//service/', '/service', Record<never, never>, Record<never, never>>,
    '//test-category/': RouteRecordInfo<'//test-category/', '/test-category', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/auth/login': RouteRecordInfo<'/auth/login', '/auth/login', Record<never, never>, Record<never, never>>,
    '/auth/login-with-token': RouteRecordInfo<'/auth/login-with-token', '/auth/login-with-token', Record<never, never>, Record<never, never>>,
  }
}
